---
- name: Filebeat Playbook
  become: true
  hosts: webservers
  tasks:

  - name: Download Filebeat Deb
    command: curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install Filebeat Deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: Copy Filebeat
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and confirgure system module
    command: filebeat modules enable system

  - name: Setup Filebeat
    command: filebeat setup -e

  - name: Start Filebeat service
    command: service filebeat start