---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:

  - name: Downlaod Metricbeat
    command: curl -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: Install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module for petric beat
    command: metricbeat modules enable docker

  - name: setup metric beat
    command: metricbeat setup -e

  - name: start metric beat
    command: service metricbeat start